[version]
# version to update to
major = 0
minor = 1
patch = 0

[paths]
# Locations of repositories to update
#
# ------------------------------------------------------
# (1) Path to  repository "smartnoise-core-python"
#   - e.g. "/Users/username/github/repos/smartnoise-core-python"
# ------------------------------------------------------
#
#python = "/Users/michael/whitenoise/python"
python = "/Users/ramanprasad/Documents/github-rp/smartnoise-core-python"
#
# ------------------------------------------------------
# (2) Path to repository "smartnoise-core"
#   - e.g. "/Users/username/github/repos/smartnoise-core-python/smartnoise-core"
#   - Normally this is the submodule within smartnoise-core-python
# ------------------------------------------------------
#
#core = "/Users/michael/whitenoise/python/smartnoise-core"
core = "/Users/ramanprasad/Documents/github-rp/smartnoise-core-python/smartnoise-core"
#
# ------------------------------------------------------
# (3) Path to the repository "smartnoise-core-r"
#  ** Currently not in use **
# ------------------------------------------------------
#
#R = "/Users/michael/smartnoise/R"
